name: Download Video from Google Drive

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Enable Git LFS
          token: ${{ secrets.GH_PAT }}
      
      - name: Setup Git LFS
        run: |
          git lfs install
          
      - name: Create videos directory if it doesn't exist
        run: mkdir -p videos
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown
      
      - name: Download video from Google Drive
        run: |
          # Extract file ID from the Google Drive URL
          FILE_ID="1GGtvDWqLZQieNmVhp0CG5pmg2LDFu4bE"
          OUTPUT_FILE="videos/stream_video.mp4"
          
          # Download the video using gdown
          gdown --id $FILE_ID -O $OUTPUT_FILE
          
      - name: Setup Git identity
        run: |
          git config --global user.name "ansentase"
          git config --global user.email "samomsan7@gmail.com"
      
      - name: Track large files with Git LFS
        run: |
          git lfs track "videos/*.mp4"
          git add .gitattributes
      
      - name: Add and commit video file
        run: |
          git add videos/stream_video.mp4
          git commit -m "Add video file from Google Drive"
          
      - name: Push changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
