name: Download and Push Google Drive Video (LFS)

on: [workflow_dispatch]  # Manual trigger

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install gdown
        run: pip install gdown

      - name: Download Video from Google Drive
        run: |
          gdown --id 1GGtvDWqLZQieNmVhp0CG5pmg2LDFu4bE --output video.mp4

      - name: Setup Git LFS and Track MP4
        run: |
          git lfs install
          git lfs track "*.mp4"
          git add .gitattributes

      - name: Commit and Push to Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "ansentase"
          git config --global user.email "samomsan7@gmail.com"
          git add video.mp4
          git commit -m "Add video.mp4 via GitHub Actions using Git LFS"
          git push https://x-access-token:${GH_PAT}@github.com/ansentase/stream.git HEAD:main
