name: YouTube Live Stream Test

on:
  workflow_dispatch:

jobs:
  teststream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download test video
        run: |
          wget https://file-examples.com/storage/fef3b37e2f154a2d90b3fd3/2017/04/file_example_MP4_480_1_5MG.mp4 -O video.mp4

      - name: Stream to YouTube
        run: |
          YOUTUBE_STREAM_KEY="1axq-th5h-t5rq-g4x1-9q7d"
          YOUTUBE_RTMP="rtmp://a.rtmp.youtube.com/live2"

          ffmpeg -re -i video.mp4 \
            -c:v libx264 -preset veryfast -b:v 2500k \
            -c:a aac -b:a 128k \
            -f flv "${YOUTUBE_RTMP}/${YOUTUBE_STREAM_KEY}"
