name: YouTube Live Stream Test

on:
  workflow_dispatch:

jobs:
  teststream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download sample video
        run: |
          wget https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4 -O video.mp4

      - name: Stream to YouTube
        run: |
          YOUTUBE_STREAM_KEY="1axq-th5h-t5rq-g4x1-9q7d"
          YOUTUBE_RTMP="rtmp://a.rtmp.youtube.com/live2"

          ffmpeg -re -i video.mp4 \
            -c:v libx264 -preset veryfast -b:v 2500k \
            -c:a aac -b:a 128k \
            -f flv "${YOUTUBE_RTMP}/${YOUTUBE_STREAM_KEY}"
