name: YouTube Live Stream

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  livestream:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Enable Git LFS to properly download large files
      
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Verify video file exists
        run: |
          ls -la videos/
          file videos/video.mp4
      
      - name: Stream to YouTube
        run: |
          # YouTube stream key
          YOUTUBE_STREAM_KEY="1axq-th5h-t5rq-g4x1-9q7d"
          
          # YouTube RTMP URL
          YOUTUBE_RTMP="rtmp://a.rtmp.youtube.com/live2"
          
          # Stream settings
          VIDEO_BITRATE="2500k"
          AUDIO_BITRATE="128k"
          FRAMERATE="30"
          
          # Stream the video to YouTube
          ffmpeg -re -i videos/video.mp4 \
                 -c:v libx264 -preset veryfast -b:v $VIDEO_BITRATE \
                 -c:a aac -b:a $AUDIO_BITRATE \
                 -f flv \
                 -flvflags no_duration_filesize \
                 "${YOUTUBE_RTMP}/${YOUTUBE_STREAM_KEY}"
