name: Edit Repository Video and Save with LFS

on:
  workflow_dispatch:

jobs:
  trim_and_overlay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GH_PAT }}

      - name: Setup Git LFS
        run: git lfs install

      - name: Install FFmpeg and fontconfig
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fontconfig

      - name: Verify input video
        run: |
          ls -la stream/videos/
          file stream/videos/video.mp4

      - name: Trim to 3s and overlay "Hello World"
        run: |
          mkdir -p lhs
          ffmpeg -i stream/videos/video.mp4 -ss 00:00:00 -t 00:00:03 \
            -vf "drawtext=text='Hello World':fontcolor=white:fontsize=36:font='FreeSerif':x=(w-text_w)/2:y=(h-text_h)/2:borderw=2:bordercolor=black" \
            -c:a copy lhs/hello_world_video.mp4

      - name: Setup Git identity
        run: |
          git config --global user.name "ansentase"
          git config --global user.email "samomsan7@gmail.com"

      - name: Track output with Git LFS
        run: |
          git lfs track "lhs/*.mp4"
          git add .gitattributes

      - name: Commit and push edited video
        run: |
          git add lhs/hello_world_video.mp4
          git commit -m "Saved 3s trimmed video with Hello World overlay to lhs/"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
