name: Download, Trim, and Overlay Video

on:
  workflow_dispatch:

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GH_PAT }}

      - name: Setup Git LFS
        run: |
          git lfs install

      - name: Create videos directory if it doesn't exist
        run: mkdir -p videos

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown

      - name: Download video from Google Drive
        run: |
          FILE_ID="1GGtvDWqLZQieNmVhp0CG5pmg2LDFu4bE"
          OUTPUT_FILE="videos/stream_video.mp4"
          gdown --id $FILE_ID -O $OUTPUT_FILE

      - name: Install FFmpeg and fontconfig
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fontconfig

      - name: Trim and overlay "Hello World" (3 seconds)
        run: |
          mkdir -p trimmed
          ffmpeg -i videos/stream_video.mp4 -ss 00:00:00 -t 00:00:03 \
            -vf "drawtext=text='Hello World':fontcolor=white:fontsize=36:font='FreeSerif':x=(w-text_w)/2:y=(h-text_h)/2:borderw=2:bordercolor=black" \
            -c:a copy trimmed/hello_world_video.mp4

      - name: Setup Git identity
        run: |
          git config --global user.name "ansentase"
          git config --global user.email "samomsan7@gmail.com"

      - name: Track large files with Git LFS
        run: |
          git lfs track "trimmed/*.mp4"
          git add .gitattributes

      - name: Commit and push edited video
        run: |
          git add trimmed/hello_world_video.mp4
          git commit -m "Add trimmed 3s video with 'Hello World' overlay"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
